name: Deployment Excerise 1
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: "04 Practice Project (Start)"

      - name: Run lint
        run: npm run lint
        working-directory: "04 Practice Project (Start)"

      - name: Run tests
        run: npm run test
        working-directory: "04 Practice Project (Start)"

      - name: Run Build
        run: npm run build
        working-directory: "04 Practice Project (Start)"

      - name: Deploy code
        run: echo "Deploying..."
        working-directory: "04 Practice Project (Start)"